Created a table in the README.md
chaoss/wg-risk pull request #130
Opened 2021-04-20 23:10 UTC by seun-beta

Signed-off-by: Seunfunmi Adegoke <51419148+seun-beta@users.noreply.github.com>

2021-04-20 23:11 UTC, seun-beta commented
@GeorgLink I created the tables in the Risk Working README.md according to the template prescribed in the Standardization google document.

2021-04-21 12:22 UTC, GeorgLink requested changes
Thanks @seun-beta 

Please add the title of the Focus Area at the top of each file.

I will leave the remaining review to more active WG members

2021-04-21 12:22 UTC, GeorgLink commented on focus-areas/business-risk/README.md
> -# Business Risk (How likely am I to be stuck with this project and no community)
Please add the Focus Area as a title.

2021-04-21 12:22 UTC, GeorgLink commented on focus-areas/code-quality/README.md
> -# Code Quality
Please add the Focus Area as a title.

2021-04-21 12:22 UTC, GeorgLink commented on focus-areas/licensing/README.md
> -# Licensing
Please add the Focus Area as a title.

2021-04-21 12:22 UTC, GeorgLink commented on focus-areas/security/README.md
> -# Security
Please add the Focus Area as a title.

2021-04-21 12:22 UTC, GeorgLink commented on focus-areas/transparency/README.md
> -# Transparency
Please add the Focus Area as a title.

2021-04-21 16:23 UTC, seun-beta commented on focus-areas/business-risk/README.md
> -# Business Risk (How likely am I to be stuck with this project and no community)
Resolved

2021-04-21 16:24 UTC, seun-beta commented on focus-areas/licensing/README.md
> -# Licensing
Resolved

2021-04-21 16:24 UTC, seun-beta commented on focus-areas/transparency/README.md
> -# Transparency
Resolved

2021-04-21 16:24 UTC, seun-beta commented on focus-areas/security/README.md
> -# Security
Resolved

2021-04-21 16:24 UTC, seun-beta commented on focus-areas/code-quality/README.md
> -# Code Quality
Resolved

2021-04-21 16:25 UTC, seun-beta commented
Thank you very much @GeorgLink for the review. I would be on stand by for more reviews from more active WG members. 

Thanks!

2021-04-22 18:41 UTC, GeorgLink commented
Thanks @seun-beta

2021-06-25 18:03 UTC, ritik-malik commented
Hi @sgoggins ,
Is this PR ready to merge?
If yes, it would be of great help for us to proceed with the process of [standardization of Working Groups repos](https://docs.google.com/document/d/1chPzgJa49sO_f3wVqp_NLJupSVyKHSVyuFuwzl4m4KI/edit#heading=h.4ejkic2mb7z1), which serves as a prerequisite for our [M.A.R.S.](https://github.com/chaoss/MARS) project, since we would be pulling focus-area goals directly from their respective READMEs

2021-06-28 14:26 UTC, klumb commented
@sgoggins where are we at on this?

2021-07-12 14:54 UTC, merged